[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-alpha6"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-alpha6"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha6"

[[dependency]]
org = "ballerina"
name = "test"
version = "0.0.0"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha6"


