[[dependency]]
org = "ballerina"
name = "test"
version = "0.0.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerina"
name = "websub"
version = "1.2.0-alpha7"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-alpha7"

[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-alpha7"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.12"
repository = "local"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha7"


